### ISSUE TITLE
Backend alle Übungen aufrufen können

### ISSUE THREAD

**Issue by LenaHaggi** [reTeaming/rehome#132]
alle Übungen (auch nicht zugewiesene) sollen aufrufbar sein

**Comment by Borajiin** [comment]
@LenaHaggi sind damit die DefaultExercise gemeint? Oder auf was bezieht sich das zugewiesen? Übungen welche nicht einem Patienten zugeordnet sind gibt es laut unserem Datenmodell ja eigentlich nicht.
