### ISSUE TITLE
Week Filter Backend

### ISSUE THREAD

**Issue by felixmattersberger** [reTeaming/rehome#56]
Dieses Issue umfasst eine Filterfunktion nach Wochen im Backend.

**Comment by Borajiin** [comment]
Es ist etwas unklar, was hier genau gefiltert werden soll. Ich nehme an, dass die jeweiligen ExerciseBlöcke damit gemeint sind, welche in der Woche gespeichert sind? Dies wird zumindest von #154 bearbeitet.
