### ISSUE TITLE
Design eines einfachen Logos

### ISSUE THREAD

**Issue by leonfuss** [reTeaming/rehome#7]
Unsere App benötigt ein einfaches Logo, das als AppIcon angezeigt werden kann. 
Es empfielt sich es möglichst minimalistisch zu halten, damit wir es in allen möglich größen (auch sehr klein) anzeigen können.

Die finale Datein sollten eine PNG in unterschiedlichen Auflösungen, sowie eine Datei als Vektorgrafik.

**Comment by felixmattersberger** [comment]
svg & png datei in Ordner assets
